### ISSUE TITLE
Not adding ojdbc8 to classpath

### ISSUE THREAD

**Issue by aquddos123** [amolenaar/fitnesse-maven-classpath#16]
We recently decided to switch to Oracle 19c and that requires us to upgrade from ojdbc7 to ojdbc8 driver in the project POM.
The project is building successfully and the new driver jar is downloading successfully but the plugin doesn't recognize therefore NOT adding to fitnesse classpath. Which is eventually giving "`java.lang.ClassNotFoundException: oracle.jdbc.driver.OracleDriver`" upon execution.

We are using latest 1.9 version of this plugin. 
Switching to ojdbc7 works fine and we can see jar file is adding to fitnesse classpath. 

```
<dependency>
           <groupId>com.oracle</groupId>
            <artifactId>ojdbc7</artifactId>
            <version>${ojdbc7.version}</version>
</dependency>
```

```
<dependency>
	<groupId>com.oracle.jdbc</groupId>
	<artifactId>ojdbc8</artifactId>
	<version>12.2.0.1</version>
</dependency>
```
```
<dependency>
         <groupId>com.oracle.ojdbc</groupId>
         <artifactId>ojdbc8</artifactId>
         <version>19.3.0.0</version>
</dependency>
```
Is this because ojdbc8 is grouped differently "com.oracle.jdbc" whereas older versions of drivers are grouped as "com.oracle" as shown above?

Any idea how to get around this issue without dealing with physical file location of the jar file?

**Comment by tcnh** [comment]
Where is this jar used? I think you'll need to change  your import as the package name may have changed, but that has nothing to do with the maven classpath plugin.

**Comment by aquddos123** [comment]
> Where is this jar used? I think you'll need to change your import as the package name may have changed, but that has nothing to do with the maven classpath plugin.

We execute few SQLs in java code to load test data as part of SuiteSetUp.

**Comment by tcnh** [comment]
Then the test code should import the new package names..

**Comment by aquddos123** [comment]
> Then the test code should import the new package names..

There are no such oracle imports to fix on our end. We are simply passing Oracle's driver class "`oracle.jdbc.driver.OracleDriver`" to Java's Connection object to create a DB connection
The import I see here is `import java.sql.Connection;` which appears t be fine with Java 8 we are using. 
https://docs.oracle.com/en/database/oracle/oracle-database/19/jajdb/oracle/jdbc/OracleDriver.html

In our project configuration, the "ojdbc8-12.2.0.1.jar" have to be included in the Classath otherwise it won't be located by the connection call. 

ojdbc7 is easily adding to the classpath as seen in the following image (classpath print in FitNesse wiki page)

![image](https://user-images.githubusercontent.com/4468089/80630534-5fdc0f80-8a22-11ea-9841-c83df5a6a4f8.png)


Question is when we switch to ojdbc8 why it is not adding to Classpath?

**Comment by tcnh** [comment]
Any chance you can share the exact dependency you're using in your pom.xml? as I can't think of any reason why the plugin would omit one specific dependency

Edit- I see you already shared it. Let me try to reproduce..

**Comment by tcnh** [comment]
Can't reproduce..

![image](https://user-images.githubusercontent.com/2232710/80643221-01398480-8a68-11ea-8351-6f03ef57cdd3.png)

with a minimal pom.xml:
![image](https://user-images.githubusercontent.com/2232710/80643259-12829100-8a68-11ea-92bb-8ee81dc81a60.png)

can you run `mvn compile` on your project? Or index it using an IDE that utilizes the same local repo directory? I suspect the jar was never copied to your local repository and thus cannot be added to the classpath.

**Comment by aquddos123** [comment]
@tcnh Thanks for a quick test. 
I tried both mvn compile and mvn install on a clean repo and confirmed jar was copied successfully. 

Sorry, I forgot to mention that we point to our internal artifactory instead of maven central for dependencies. There, I see that POM is missing with ojdbc8 driver whereas older drivers have POM file in addition to Jar file. Do you think this could be the issue?

Artifactory snapshot:

![image](https://user-images.githubusercontent.com/4468089/80644541-ce779800-8a37-11ea-9064-6a9aab997388.png)

**Comment by tcnh** [comment]
Not sure.. I imagine MavenProject.getTestClasspathElements() requires the pom for further dependency lookup. If you can find a similar situation in your artifactory repo you may be able to confirm if that's the problem. 

It is a bit weird though, because the pom is present in other repo's (that I suspect just mirror oracle's?). Or do you by any chance deploy it to artifactory yourself?

**Comment by aquddos123** [comment]
Update: 
I pointed to public artifactory and it worked fine. I can see ojdbc8 adding to classpath successfully. 
It seems like internal artifactory issue. I need to follow up with the DevOps team. 

I think we can close this ticket until we see any other reason to open. 
Thanks for your help @tcnh
