### ISSUE TITLE
Support FitNesse 20150114

### ISSUE THREAD

**Issue by fhoeben** [amolenaar/fitnesse-maven-classpath#6]
Currently the plugin does not work with FitNesse 20150114 (or compile when that version is put in this project's pom.xml). Can you address this?

I've seen:
- a problem with a reference to 'Maybe', easily fixed.
- in a unit test a reference to 'ParserTestHelper', to me not immediately clear how to fix that.

**Comment by amolenaar** [comment]
Also release version 1.8.
